Завдання 1

Вправа 1. Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [11]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_1(n):
    arr = np.zeros((n, n), dtype=int) 
    np.fill_diagonal(arr, np.arange(1, n+1)) 
    print(arr)
task_1(5)
print('Execution time: ', datetime.datetime.now() - start_time)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Execution time:  0:00:00.000997


In [1]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()

def task_1(n):
    arr = [[0 for i in range(n)] for j in range(n)] 
    for i in range(n):
        arr[i][i] = i + 1 
        if i < n-1:
            arr[i+1][i] = 0 
    print(arr)
task_1(5)
print('Execution time: ', datetime.datetime.now() - start_time)

[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]
Execution time:  0:00:00.000997


Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру
n×m, в якому в кожному рядку з номером r і в кожному стовпчику з
номером c стоять 0, а інші елементи дорівнюють 1.

In [17]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_3(n, m, r, c):
    arr = np.ones((n, m), dtype=int) 
    arr[r, :] = 0 
    arr[:, c] = 0 
    print(arr)

task_3(6, 7, 2, 3)
print('Execution time: ', datetime.datetime.now() - start_time)

[[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]]
Execution time:  0:00:00.000997


In [49]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_3(n, m, r, c):

    arr = [[1 for j in range(m)] for i in range(n)]
    
    for j in range(m):
        arr[r][j] = 0
        
    for i in range(n):
        arr[i][c] = 0
        
    for i in range(n):
        print('[', end='')
        for j in range(m):
            print(str(arr[i][j]), end=' ')
        print('],')
    
task_3(6, 7, 2, 3)
print('Execution time: ', datetime.datetime.now() - start_time)

[1 1 1 0 1 1 1 ],
[1 1 1 0 1 1 1 ],
[0 0 0 0 0 0 0 ],
[1 1 1 0 1 1 1 ],
[1 1 1 0 1 1 1 ],
[1 1 1 0 1 1 1 ],
Execution time:  0:00:00.001995


Вправа 4. Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.

In [18]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_4(n, m):
    matrix = np.zeros((n, m), dtype=int) 
    matrix[0, :] = np.arange(m)  
    print(matrix)

task_4(3, 4)
print('Execution time: ', datetime.datetime.now() - start_time)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Execution time:  0:00:00.000997


In [19]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()

def task_4(n, m):

    matrix = []
    
    for i in range(n):
        row = []
        for j in range(m):
            if i == 0:
                row.append(j)
            else:
                row.append(0)
        matrix.append(row)
        
    for i in range(n):
        print(matrix[i])

task_4(3, 4)
print('Execution time: ', datetime.datetime.now() - start_time)

[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
Execution time:  0:00:00.000998


Вправа 5. Вводиться число n. Вивести масив розміру n×n, в
якому в рядках з парними індексами стоять 1, а в інших – 0.

In [22]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()
def task_5(n):
    result_array = np.zeros((n, n))
    result_array[::2] = 1

    print(result_array.astype(int))
task_5(5)
print('Execution time: ', datetime.datetime.now() - start_time)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
Execution time:  0:00:00.000996


In [23]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()

def task_5(n):
    result_array = [[0 for j in range(n)] for i in range(n)]
    for i in range(n):
        if i % 2 == 0:
            for j in range(n):
                result_array[i][j] = 1
    print(result_array)
task_5(5)
print('Execution time: ', datetime.datetime.now() - start_time)

[[1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1]]
Execution time:  0:00:00.000997


Вправа 10. Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [24]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_10(n, m):
    arr = np.random.random((n, m))

    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    
    arr_min = round(arr_min, 3)
    arr_max = round(arr_max, 3)
    arr_mean = round(arr_mean, 3)
    arr_std = round(arr_std, 3)
    
    print("Мінімум:", arr_min)
    print("Максимум:", arr_max)
    print("Середнє:", arr_mean)
    print("Дисперсія:", arr_std)

task_10(4, 5)
print('Execution time: ', datetime.datetime.now() - start_time)

Мінімум: 0.019
Максимум: 0.994
Середнє: 0.469
Дисперсія: 0.337
Execution time:  0:00:00.001995


In [27]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import random
import datetime

start_time = datetime.datetime.now()

def task_10(n, m):
    arr = [[random.random() for j in range(m)] for i in range(n)]
    
    arr_min = float('inf')
    arr_max = float('-inf')
    arr_sum = 0
    arr_sum_squared = 0
    count = 0
    
    for i in range(n):
        for j in range(m):
            value = arr[i][j]
            arr_min = min(arr_min, value)
            arr_max = max(arr_max, value)
            arr_sum += value
            arr_sum_squared += value ** 2
            count += 1
            
    arr_mean = arr_sum / count
    arr_std = ((arr_sum_squared / count) - (arr_mean ** 2)) ** 0.5
    
    arr_min = round(arr_min, 3)
    arr_max = round(arr_max, 3)
    arr_mean = round(arr_mean, 3)
    arr_std = round(arr_std, 3)

    print("Мінімум:", arr_min)
    print("Максимум:", arr_max)
    print("Середнє:", arr_mean)
    print("Дисперсія:", arr_std)

task_10(4, 5) 
print('Execution time: ', datetime.datetime.now() - start_time)

Мінімум: 0.007
Максимум: 0.892
Середнє: 0.413
Дисперсія: 0.284
Execution time:  0:00:00.000998


Вправа 12. Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [39]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_12(n):
    arr = np.ones((n, n))
    
    arr[0,:] = 0
    arr[n-1,:] = 0
    arr[:,0] = 0
    arr[:,n-1] = 0
    
    print(arr.astype(int))

task_12(4)
print('Execution time: ', datetime.datetime.now() - start_time)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
Execution time:  0:00:00.000998


In [31]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()

def task_12(n):

    arr = [[1 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        for j in range(n):
            if i == 0 or i == n-1 or j == 0 or j == n-1:
                arr[i][j] = 0
                
    print(arr)

task_12(4)
print('Execution time: ', datetime.datetime.now() - start_time)

[[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]
Execution time:  0:00:00.000986


Вправа 16. Заповнити вектор значеннями від 0 до n. Всі значення,
що більші за n/4 та менші за 3n/4 замінити нулями.

In [32]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()

def task_16(n):
    
    vec = np.arange(n + 1)
    vec[(vec > n/4) & (vec < 3*n/4)] = 0
    
    print(vec)

task_16(10)
print('Execution time: ', datetime.datetime.now() - start_time)

[ 0  1  2  0  0  0  0  0  8  9 10]
Execution time:  0:00:00.000998


In [36]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()
def task_16(n):
    
    vec = []
    
    for i in range(n + 1):
        vec.append(i)
    
    for i in range(n + 1):
        if (vec[i] > n/4) and (vec[i] < 3*n/4):
            vec[i] = 0
    
    for i in range(n + 1):
        print(vec[i])
        
task_16(10)
print('Execution time: ', datetime.datetime.now() - start_time)

0
1
2
0
0
0
0
0
8
9
10
Execution time:  0:00:00.000994


Вправа 17. Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за n/2 та більші за 3n/4 на
протилежні.

In [37]:
# з використанням універсальних функцій бібліотеки NumPy
import datetime

start_time = datetime.datetime.now()
import numpy as np

def task_17(n):
    
    vec = np.arange(n + 1)
    vec[(vec < n/2) | (vec > 3*n/4)] *= -1
    
    print(vec)
task_17(10)
print('Execution time: ', datetime.datetime.now() - start_time)

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
Execution time:  0:00:00.000995


In [38]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()
def task_17(n):
    vec = []

    for i in range(n + 1):
        vec.append(i)

    for i in range(n + 1):
        if vec[i] < n/2 or vec[i] > 3*n/4:
            vec[i] *= -1

    for i in range(n + 1):
        print(vec[i])
task_17(10)
print('Execution time: ', datetime.datetime.now() - start_time)

0
-1
-2
-3
-4
5
6
7
-8
-9
-10
Execution time:  0:00:00.000953


Вправа 21. Ввести числа n і m. Згенерувати матрицю n×n
випадкових цілих елементів з діапазону [0, m]. Замінити всі
максимальні елементи цієї матриці на протилежні за знаком.

In [16]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np

def task_21(n, m):
    matrix = np.random.randint(0, m+1, size=(n, n))
    
    print("Початковий вектор: ")
    print(matrix)
    
    max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
    matrix[max_index] = -matrix[max_index]
    
    print("Змінений вектор: ")
    print(matrix)

task_21(4, 10)

Початковий вектор: 
[[ 2 10  0  3]
 [ 2  3  7  9]
 [ 5  6  4  2]
 [ 7  9  7  1]]
Змінений вектор: 
[[  2 -10   0   3]
 [  2   3   7   9]
 [  5   6   4   2]
 [  7   9   7   1]]


In [17]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import random

def task_21(n, m):
    matrix = []
    
    for i in range(n):
        row = []
        for j in range(n):
            row.append(random.randint(0, m))
        matrix.append(row)
        
    print("Початковий вектор: ")
    for i in range(n):
        for j in range(n):
            print(matrix[i][j], end=" ")
        print()
            
    max_element = matrix[0][0]
    for i in range(n):
        for j in range(n):
            if matrix[i][j] > max_element:
                max_element = matrix[i][j]
                    
    for i in range(n):
        for j in range(n):
            if matrix[i][j] == max_element:
                matrix[i][j] = -matrix[i][j]

    print("Змінений вектор: ")
    for i in range(n):
        for j in range(n):
            print(matrix[i][j], end=" ")
        print()
        
task_21(4, 10)

Початковий вектор: 
2 4 5 3 
10 4 8 9 
2 0 1 1 
10 9 7 6 
Змінений вектор: 
2 4 5 3 
-10 4 8 9 
2 0 1 1 
-10 9 7 6 


Завдання 2

Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку.
\begin{cases}
2 x_1 - x_2 + 3 x_3 + 2 x_4 = 4 \\
3 x_1 + 3 x_2 + 3 x_3 + 2 x_4 = 6 \\
3 x_1 - x_2 - x_3 + 2 x_4 = 6 \\
3 x_1 - x_2 + 3 x_3 - x_4 = 6 \\
\end{cases}

In [40]:
import numpy as np

rtol = 1e-05
atol = 1e-08

A = np.array([[2, -1, 3, 2], [3, 3, 3, 2], [3, -1, -1, 2], [3, -1, 3, -1]])

B = np.array([4, 6, 6, 6])

det_A = np.linalg.det(A)

det_x1 = np.linalg.det(np.column_stack((B, A[:, 1:],)))
det_x2 = np.linalg.det(np.column_stack((A[:, 0], B, A[:, 2:],)))
det_x3 = np.linalg.det(np.column_stack((A[:, :2], B, A[:, 3:],)))
det_x4 = np.linalg.det(np.column_stack((A[:, :3], B)))

x1 = det_x1 / det_A
x2 = det_x2 / det_A
x3 = det_x3 / det_A
x4 = det_x4 / det_A

print("x1 =", x1.round(2))
print("x2 =", x2.round(2))
print("x3 =", x3.round(2))
print("x4 =", x4.round(2))

x = np.array([x1, x2, x3, x4]).reshape((-1, 1))

def checkWithMatrixMultiplication(A, B, x):    
    Ax = np.dot(A, x).flatten().astype(int)

    res = np.allclose(Ax, B, rtol, atol)
    print ("Сheck for correctness of the solution using matrix multiplication: ", res)
    
    
def checkWithInverseMatrix(A, B, x):
    x = np.array([x1, x2, x3, x4]).reshape((-1, 1)).flatten().astype(int)
    A_inv = np.linalg.inv(A)
    temp_x = np.dot(A_inv, B).astype(int)
    
    res = np.allclose(temp_x, x.flatten().astype(int), rtol, atol)
    print ("Check the correctness of the solution using the inverse matrix: ", res)

def checkWithNumPy(A, B, x):
    temp_x = np.linalg.solve(A, B).astype(int)
    
    res = np.allclose(temp_x, x.flatten().astype(int), rtol, atol)
    print ("Check the correctness of the solution using numpy.linalg.solve(): ", res)
    
    
checkWithMatrixMultiplication(A, B, x)
checkWithInverseMatrix(A, B, x)
checkWithNumPy(A, B, x)

x1 = 2.0
x2 = 0.0
x3 = 0.0
x4 = 0.0
Сheck for correctness of the solution using matrix multiplication:  True
Check the correctness of the solution using the inverse matrix:  True
Check the correctness of the solution using numpy.linalg.solve():  True


Завдання 3

Обчислити значення матричного виразу

\begin{equation*} 
(A - B)A - 3B
\end{equation*}

\begin{equation*} 
A = \begin{pmatrix}
3 & 2 & -5 \\
4 & 2 & 0 \\
1 & 1 & 2
\end{pmatrix},
B = \begin{pmatrix}
-1 & 2 & 4 \\
0 & 3 & 2 \\
-1 & -3 & 4
\end{pmatrix}
\end{equation*}


In [8]:
# з використанням універсальних функцій бібліотеки NumPy
import numpy as np
import datetime

start_time = datetime.datetime.now()
def valueOfTheMatrixExpression(A, B):
    result = np.dot(A - B, A) + 3 * B
    print(result)
    
A = np.array([[3, 2, -5], [4, 2, 0], [1, 1, 2]])
B = np.array([[-1, 2, 4], [0, 3, 2], [-1, -3, 4]])

valueOfTheMatrixExpression(A, B)
print('Execution time: ', datetime.datetime.now() - start_time)

[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]
Execution time:  0:00:00.000996


In [9]:
# за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
import datetime

start_time = datetime.datetime.now()
def valueOfTheMatrixExpression(A, B):
    
    C = [[0 for _ in range(len(A))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A)):
            C[i][j] = A[i][j] - B[i][j]
            
    D = [[0 for _ in range(len(A))] for _ in range(len(A))]
    for i in range(len(C)):
        for j in range(len(A[0])):
            for k in range(len(A)):
                D[i][j] += C[i][k] * A[k][j]
                
    E = [[0 for _ in range(len(B))] for _ in range(len(B))]
    for i in range(len(B)):
        for j in range(len(B[0])):
            E[i][j] = 3 * B[i][j]
            
    result = [[0 for _ in range(len(D))] for _ in range(len(D))]
    for i in range(len(D)):
        for j in range(len(D[0])):
            result[i][j] = D[i][j] + E[i][j]
            
    print(result)


A = np.array([[3, 2, -5], [4, 2, 0], [1, 1, 2]])
B = np.array([[-1, 2, 4], [0, 3, 2], [-1, -3, 4]])

valueOfTheMatrixExpression(A, B)
print('Execution time: ', datetime.datetime.now() - start_time)

[[0, 5, -26], [6, 13, -18], [17, 1, -2]]
Execution time:  0:00:00.001011
